// @taor/tools — type definitions (no runtime deps from sibling packages)

import type { ToolCall } from "@taor/core"

// ─── JSONSchema (JSON Schema Draft-07 minimum viable superset) ───
//
// This is a superset of what Anthropic/OpenAI tool-calling APIs accept.
// It must be broad enough to represent the output of `zodToJsonSchema()`
// for any realistic Zod schema users might pass to `defineTool()`.
//
// Design constraint: `JSONSchema` is the canonical parameter format that
// flows from tool definition → ToolRegistry → LLM Adapter → API request.
// It is NOT validated at tool registration time (validation is the
// adapter's responsibility), but it MUST structurally accommodate all
// valid JSON Schema shapes generated by zod-to-json-schema.

export interface JSONSchema {
  /** Top-level type. Optional because `anyOf`/`oneOf`/`allOf` schemas
   *  do not require a top-level `type` (Draft-07 §6.1.2). */
  type?: string | string[]
  properties?: Record<string, JSONSchemaProperty>
  required?: string[]
  additionalProperties?: boolean
  description?: string
  /** @see JSON Schema Draft-07 §6.7 */
  anyOf?: JSONSchema[]
  /** @see JSON Schema Draft-07 §6.7 */
  oneOf?: JSONSchema[]
  /** @see JSON Schema Draft-07 §6.7 */
  allOf?: JSONSchema[]
  /** Enum values at the schema level (Draft-07 §6.1.2) */
  enum?: unknown[]
  /** Const value (Draft-07 §6.1.3) */
  const?: unknown
  /** @see JSON Schema Draft-07 §7.3 */
  $ref?: string
  /** Default value (Draft-07 §9.2) */
  default?: unknown
}

export interface JSONSchemaProperty {
  type?: string | string[]
  description?: string
  enum?: unknown[]
  const?: unknown
  items?: JSONSchemaProperty
  properties?: Record<string, JSONSchemaProperty>
  required?: string[]
  anyOf?: JSONSchemaProperty[]
  oneOf?: JSONSchemaProperty[]
  allOf?: JSONSchemaProperty[]
  $ref?: string
  default?: unknown
  minimum?: number
  maximum?: number
  minLength?: number
  maxLength?: number
  pattern?: string
}

// ─── Tool result ───

export type ToolResult<T = unknown> =
  | { ok: true; data: T; meta?: ToolResultMeta }
  | { ok: false; error: string; code: ToolErrorCode; recoverable: boolean }

export interface ToolResultMeta {
  duration: number
  tokensUsed?: number
  artifacts?: string[]
  truncated?: boolean
}

export type ToolErrorCode =
  | "timeout"
  | "permission_denied"
  | "invalid_params"
  | "execution_failed"
  | "aborted"
  | "unknown"

// ─── Permissions & risk ───

export type PermissionHint = "fs-read" | "fs-write" | "network" | "shell" | "subprocess"
export type RiskLevel = "low" | "medium" | "high"

// ─── Retry ───

export interface RetryPolicy {
  maxRetries: number
  backoff: "fixed" | "exponential" | "linear"
  baseDelayMs: number
  maxDelayMs?: number
}

// ─── Predicates ───

export type ApprovalPredicate = (params: unknown, ctx: ToolContext) => boolean

// ─── Tool context (injected at execute time) ───

export interface ToolContext {
  session: import("@taor/core").SessionState
  turn: import("@taor/core").TurnState
  signal: AbortSignal
  logger: import("@taor/core").Logger
}

// ─── ToolDescriptor (internal normalized representation) ───

/**
 * Internal normalized representation of a tool.
 *
 * ## Type erasure boundary
 *
 * `execute` and all hook callbacks use `unknown` for `params` and
 * `ToolResult` (equivalent to `ToolResult<unknown>`) for return values.
 * This is intentional — `ToolDescriptor` is the schema-agnostic normalization
 * layer. Typed wrappers in `defineTool()` / `Tool.toDescriptor()` provide
 * compile-time type safety; **runtime validation of params against
 * `parameters` (JSON Schema) is the TAOR loop's responsibility** (the
 * ACT phase must validate before calling `execute()`).
 *
 * The `data` generic in `ToolResult<T>` is lost at this boundary —
 * consumers receive `ToolResult` (data = `unknown`). Callers that need
 * typed data should use `defineTool()`'s return value directly rather
 * than round-tripping through `ToolDescriptor`.
 */
export interface ToolDescriptor {
  name: string
  description: string
  /** JSON Schema for the tool's input parameters.
   *  Used by adapters to format LLM tool definitions AND by the TAOR loop
   *  to validate params before calling `execute()`. */
  parameters: JSONSchema
  execute: (params: unknown, ctx: ToolContext) => Promise<ToolResult>
  permissions?: PermissionHint[]
  risk?: RiskLevel
  timeout?: number
  retry?: RetryPolicy
  requiresApproval?: boolean | ApprovalPredicate
  onBeforeExecute?: (params: unknown, ctx: ToolContext) => Promise<void>
  onAfterExecute?: (params: unknown, result: ToolResult, ctx: ToolContext) => Promise<void>
  onError?: (params: unknown, error: Error, ctx: ToolContext) => Promise<ToolResult<never>>
}

// ─── ToolConstructor (structural — avoids importing Tool from base.ts) ───

/**
 * Constructor type for Tool subclasses. Zero-argument instantiation only.
 *
 * ## Design tradeoff: structural vs nominal
 *
 * This type is defined **structurally** (`{ toDescriptor(): ToolDescriptor }`)
 * rather than importing the `Tool` abstract class from `base.ts`. Reason:
 * `types.ts` must remain free of value imports from sibling files to avoid
 * circular dependency chains (`base.ts` already imports types from this file).
 *
 * The downside: any class with a matching `toDescriptor()` method is accepted,
 * even if it doesn't extend `Tool`. This is an accepted risk — the practical
 * harm is minimal because (a) `toDescriptor()` must return a valid
 * `ToolDescriptor` to be useful, and (b) `ToolRegistry.register()` only
 * accesses `.toDescriptor()`.
 *
 * The zero-argument constraint reflects `ToolRegistry.register()`'s actual
 * behavior: it calls `new input()` with no arguments. Tool subclasses that
 * need constructor parameters should be manually instantiated and their
 * `toDescriptor()` result passed to `register()` instead.
 *
 * @see ToolRegistry.register
 */
export type ToolConstructor = new () => {
  toDescriptor(): ToolDescriptor
}

// ─── ToolInput (accepted by HarnessConfig, ToolRegistry.register) ───

/**
 * Mixed array of tool definitions accepted by the system.
 * - `ToolDescriptor` objects: from `defineTool()` or `tool()`
 * - `ToolConstructor` classes: `class extends Tool` with zero-arg constructor
 */
export type ToolInput = ToolDescriptor | ToolConstructor
